### ISSUE TITLE
workflow exits if one task fails

### ISSUE THREAD

**Issue by rarmatei** [nrwl/ci#22] opened 2022-07-22 10:45 UTC
# Issue summary

PR to repro the issue: https://github.com/rarmatei/nx-deploy-test-2/pull/23
([See the YML directly](https://github.com/rarmatei/nx-deploy-test-2/blob/nrwl-workflow-example/.github/workflows/ci.yml))

If I run 3 targets:
- `affected --target=test` 
- `affected --target=60s-delay-fail` --> waits 60s, then fails (defined with `run-commands` + `sleep 20` + `ls <non-existent-folder>`
- `affected --target=20s-delay-fail` --> waits 20s, then fails

If I use the workflow, I will get only 1 task on my github comment: 

<img width="946" alt="image" src="https://user-images.githubusercontent.com/5975076/180412287-c10fd02f-4698-4ad3-8e55-0165902fc042.png">

The moment the "tests" fail, it will shutdown every other task, and the NxAPI will not have a chance to mark them as completed. I am setting `NX_CLOUD_DISTRIBUTED_EXECUTION_STOP_AGENTS_ON_FAILURE=false` explicitly.

**I don't believe this is an NxAPI issue however - if you watch the Agent logs, you will see the Main agent move over to shutting down ALL agents the moment the tests fail, even if the `60s-delay-fail` task hasn't finished.**

# Simplified issue 

Let's simplify the set-up and remove the Nrwl Workflow and Distributed Task Execution: https://github.com/rarmatei/nx-deploy-test-2/pull/24 
([See the YML directly](https://github.com/rarmatei/nx-deploy-test-2/blob/simple-broken-workflow-example/.github/workflows/ci.yml))

We get the same broken comment:

<img width="940" alt="image" src="https://user-images.githubusercontent.com/5975076/180419437-e096cd4f-b8eb-47bd-8c2e-3b8101c676b0.png">

If you pull the below into a local script and run it, **it will correctly wait for all tasks to finish before shutting down**:

```
pids=()

npx nx affected --target=test --base=origin/main &
pids+=($!)

npx nx affected --target=60s-delay-fail --base=origin/main &
pids+=($!)

npx nx affected --target=20s-delay-fail --base=origin/main &
pids+=($!)

for pid in "${pids[@]}"; do
  wait "$pid"
done
```

So this seems to be a problem only in an Github Action context.

What's more interesting, is that, **if you remove the test from the above script and you re-submit it, it will CORRECTLY wait for all tasks to finish**:

```
pids=()

# remove the tests and now it works even on Github Actions
# npx nx affected --target=test --base=origin/main &
# pids+=($!)

npx nx affected --target=60s-delay-fail --base=origin/main &
pids+=($!)

npx nx affected --target=20s-delay-fail --base=origin/main &
pids+=($!)

for pid in "${pids[@]}"; do
  wait "$pid"
done
```

So there seems to be something about how the tests exit that causes the Github Actions step to end prematurely. And this seems to be affecting our workflow as well.

# How to make it work

If we use a slightly different approach to run all tasks in parallel, it seems to work, and correctly displays all tasks in the comment: https://github.com/rarmatei/nx-deploy-test-2/pull/25
([See the YML directly](https://github.com/rarmatei/nx-deploy-test-2/blob/simple-working-workflow-example/.github/workflows/ci.yml))

<img width="935" alt="image" src="https://user-images.githubusercontent.com/5975076/180419497-be928cbf-5c5a-43b1-ae87-331947355c6a.png">

I don't think I understand bash/Github actions well enough to understand what's happening here, and why it would work in this case.

**Comment by JamesHenry** [comment] 2022-07-22 11:15
As discussed on slack, this is currently the case by design to avoid users wasting Github build minutes in the common case.

We can add an option for users to not “fail fast” to address this though

**Comment by meeroslav** [comment] 2022-11-07 13:28
@rarmatei do you want to follow up on this or should we close it?

**Comment by rarmatei** [comment] 2022-11-07 13:37
So currently if someone wants to configure their github actions CI to always run all tasks on each PR, instead of stopping at the first failed one, I don't think it will work. 

I can see this being valuable to reduce PR iterations: you'll see all fails your changes produce immediately, rather than fixing and finding out about them one by one.

But, as James said, they will consume their build minutes more quickly. So I think it's still a good default to fail fast. 

We [do allow users to configure this behaviour in NxCloud](https://nx.dev/nx-cloud/set-up/set-up-dte#--stop-agents-on-failure). But we don't support it in this workflow. So not sure if we want it here as well.

Up to you and James if you want to support this, otherwise I don't mind closing it 👍

**Comment by meeroslav** [comment] 2022-11-07 13:40
Ok, then let's skip it for the time being and we can come back to it later if there's a need.

**Closed as completed by meeroslav** 2022-11-07 13:40 UTC
